Repository mcQA-suite/mcQA, pull requests merged in 2019-08, with the labels that each got.

#31 Add a Codacy badge to README.md
  README.md
Labels: documentation

#32 pylint errors
  mcqa/models/model.py
Labels: enhancement

#35 More benchmark datasets
  README.md
Labels: documentation, enhancement

#36 [MRG] Refactoring & fixing flake8 issues
  docs/conf.py
  examples/pipeline.py
  mcqa/data/__init__.py
  mcqa/data/mcqa_data.py
  mcqa/data/utils.py
  mcqa/models/model.py
  mcqa/tests/conftest.py
  mcqa/tests/test_data_utils.py
  mcqa/tests/test_mcqa_data.py
  mcqa/tests/test_model.py
  setup.py
Labels: enhancement

#38 add logo in readme
  README.md
Labels: documentation, enhancement
